---

- name: Install Cloud SDK from APT
  include_tasks: install_from_apt.yml
  when: gcloud_install_from_apt | bool

- name: Install Cloud SDK from an archive
  include_tasks: install_from_archive.yml
  when: gcloud_install_from_archive | bool

- name: Uninstall Cloud SDK installed with APT
  include_tasks: uninstall_apt.yml
  when: not gcloud_install_from_apt | bool
