---

- name: Ensure temp path exists
  file:
    path: "{{ gcloud_tmp_path }}"
    state: directory

- name: Ensure install path exists
  file:
    path: "{{ gcloud_install_path }}"
    state: directory

- name: Set installation package path
  set_fact:
    gcloud_archive_path: "{{ gcloud_tmp_path }}/{{ gcloud_archive_name }}"

- name: Download the archive
  get_url:
    url: "{{ gcloud_archive_url }}/{{ gcloud_archive_name }}"
    dest: "{{ gcloud_archive_path }}"

- name: Remove existing google-cloud-sdk dir, it if exists
  file:
    path: "{{ gcloud_install_path }}/google-cloud-sdk"
    state: absent

- name: Extract Cloud SDK archive
  unarchive:
    src: "{{ gcloud_archive_path }}"
    dest: "{{ gcloud_install_path }}"
    creates: "{{ gcloud_install_path }}/google-cloud-sdk"

- name: Build run script
  template:
    src: "{{ role_path }}/templates/run_install.sh.j2"
    dest: "{{ gcloud_tmp_path }}/run_install.sh"
    mode: 0755
  tags:
    - copy
    - download

- name: Install Google Cloud SDK
  command: "{{ gcloud_tmp_path }}/run_install.sh"
  changed_when: true

- name: Remove the archive
  file:
    path: "{{ gcloud_archive_path }}"
    state: absent

- name: Remove the script
  file:
    path: "{{ gcloud_tmp_path }}/run_install.sh"
    state: absent
  when: not gcloud_debug
