---

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "default.yml"
      paths: vars

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: install.yml
  when: ansible_os_family == 'Darwin'

- include: shell.yml
  when: gcloud_setup_shell