---

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "os/{{ ansible_distribution }}.yml"
        - "os/{{ ansible_os_family }}.yml"
        - "default.yml"
      paths: vars

- name: Install Cloud SDK on Debian-based systems
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Cloud SDK on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Setup Cloud SDK in shell scripts
  include_tasks: shell.yml
  when: gcloud_setup_shell|bool
