---

- name: Setup
  include_tasks: setup.yml

- name: Install Cloud SDK on Debian-based systems
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Cloud SDK on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Setup Cloud SDK in shell scripts
  include_tasks: shell.yml
  when: gcloud_setup_shell | bool
