---

- name: Resolve .zshrc symlink
  set_fact:
    gcloud_zshrc_path: "{{ gcloud_zshrc_st.stat.lnk_source }}"
  when: gcloud_zshrc_st.stat.islnk

- name: Check whether CLOUDSDK_ROOT_DIR is defined in .zshrc
  command: grep -Fq "export CLOUDSDK_ROOT_DIR=" {{ gcloud_zshrc_path }}
  register: check_zshrc
  ignore_errors: true
  changed_when: false
  failed_when: false

- name: Load Google Cloud SDK in .zshrc when installed from archive
  blockinfile:
    dest: "{{ gcloud_zshrc_path }}"
    block: |
      # Created by markosamuli.gcloud Ansible role
      if [ -d "$HOME{{ gcloud_install_dir }}/google-cloud-sdk" ]; then
        export CLOUDSDK_ROOT_DIR="$HOME{{ gcloud_install_dir }}/google-cloud-sdk"
        # Update PATH for the Google Cloud SDK.
        source $CLOUDSDK_ROOT_DIR/path.zsh.inc
        # Enable zsh completion for gcloud.
        source $CLOUDSDK_ROOT_DIR/completion.zsh.inc
      fi
  when: gcloud_install_from_archive and check_zshrc.rc != 0

- name: Load Google Cloud SDK in .zshrc when installed from APT
  blockinfile:
    dest: "{{ gcloud_zshrc_path }}"
    block: |
      # Created by markosamuli.gcloud Ansible role
      if [ -d "/usr/share/google-cloud-sdk" ]; then
        # Enable zsh completion for gcloud.
        source /usr/share/google-cloud-sdk/completion.zsh.inc
      fi
  when: gcloud_install_from_apt
