---

- name: Check whether .bashrc file exists
  stat:
    path: "{{ gcloud_bashrc_path }}"
  register: gcloud_bashrc_st

- name: Setup bash
  include_tasks: shell_bash.yml
  when: gcloud_bashrc_st.stat.exists

- name: Check whether .zshrc exists
  stat:
    path: "{{ gcloud_zshrc_path }}"
  register: gcloud_zshrc_st

- name: Setup zsh
  include_tasks: shell_zsh.yml
  when: gcloud_zshrc_st.stat.exists
