---

- name: Check whether {{ gcloud_home }}/.bashrc exists
  stat:
    path: "{{ gcloud_home }}/.bashrc"
  register: gcloud_bashrc_st

- name: Check whether CLOUDSDK_ROOT_DIR is defined in {{ gcloud_home }}/.bashrc
  command: grep -Fq "export CLOUDSDK_ROOT_DIR=" {{ gcloud_home }}/.bashrc
  register: check_bashrc
  ignore_errors: True
  changed_when: False
  failed_when: False
  when: gcloud_bashrc_st.stat.exists

- name: Load Google Cloud SDK in {{ gcloud_home }}/.bashrc
  blockinfile:
    dest: "{{ gcloud_home }}/.bashrc"
    block: |
      # Created by markosamuli.gcloud Ansible role
      # Load Google Cloud SDK from $HOME/opt, then $HOME and finally /opt
      if [ -d "$HOME/opt/google-cloud-sdk" ]; then
        export CLOUDSDK_ROOT_DIR="$HOME/opt/google-cloud-sdk"
      elif [ -d "$HOME/google-cloud-sdk" ]; then  
        export CLOUDSDK_ROOT_DIR="$HOME/google-cloud-sdk"
      elif [ -d "/opt/google-cloud-sdk" ]; then
        export CLOUDSDK_ROOT_DIR="/opt/google-cloud-sdk"
      fi

      if [ -n "$CLOUDSDK_ROOT_DIR" ]; then
        # The next line updates PATH for the Google Cloud SDK.
        source $CLOUDSDK_ROOT_DIR/path.bash.inc
        # The next line enables bash completion for gcloud.
        source $CLOUDSDK_ROOT_DIR/completion.bash.inc
      fi
  when: gcloud_bashrc_st.stat.exists and check_bashrc.rc != 0

- name: Check whether {{ gcloud_home }}/.zshrc exists
  stat:
    path: "{{ gcloud_home }}/.zshrc"
  register: gcloud_zshrc_st

- name: Check whether CLOUDSDK_ROOT_DIR is defined in {{ gcloud_home }}/.zshrc
  command: grep -Fq "export CLOUDSDK_ROOT_DIR=" {{ gcloud_home }}/.zshrc
  register: check_zshrc
  ignore_errors: True
  changed_when: False
  failed_when: False
  when: gcloud_zshrc_st.stat.exists

- name: Load Google Cloud SDK in {{ gcloud_home }}/.zshrc
  blockinfile:
    dest: "{{ gcloud_home }}/.zshrc"
    block: |
      # Created by markosamuli.gcloud Ansible role
      # Load Google Cloud SDK from $HOME/opt, then $HOME and finally /opt
      if [ -d "$HOME/opt/google-cloud-sdk" ]; then
        export CLOUDSDK_ROOT_DIR="$HOME/opt/google-cloud-sdk"
      elif [ -d "$HOME/google-cloud-sdk" ]; then  
        export CLOUDSDK_ROOT_DIR="$HOME/google-cloud-sdk"
      elif [ -d "/opt/google-cloud-sdk" ]; then
        export CLOUDSDK_ROOT_DIR="/opt/google-cloud-sdk"
      fi

      if [ -n "$CLOUDSDK_ROOT_DIR" ]; then
        # The next line updates PATH for the Google Cloud SDK.
        source $CLOUDSDK_ROOT_DIR/path.zsh.inc
        # The next line enables zsh completion for gcloud.
        source $CLOUDSDK_ROOT_DIR/completion.zsh.inc
      fi
  when: gcloud_zshrc_st.stat.exists and check_zshrc.rc != 0
